name=ESP32 Random Utilities
version=1.1.0
author=Andrei Martchouk
maintainer=github@martchouk.com
sentence=Hardware-based random number tools for ESP32
paragraph=Includes uniform, Gaussian, weighted, and Markov chain random utilities using esp_random(). Designed for simulations, games, visuals, and procedural logic on ESP32.
category=Signal Input/Output
url=https://github.com/martchouk/esp32-random-utils
architectures=esp32
includes=rnd.hpp
